// faupp.hpp

#ifndef FauppParser_h_included
#define FauppParser_h_included

// Header file of FauppParser base clase (FauppParserBase).
// This file is automatically generated by bisonc++, from faupp-parser.yy.
//#include "../phantom-dir/faupp-parser-phantom.hpp"

#include "../faudata.hpp"
#include "lexer/lexer.hpp"

// Auto-implemented functions means functions automatically implemented in file
//      - ../phantom_dir/favpp-parser-phantom.cpp
class Faupp : public FauppBase,
              public freealgview::fauFunctor<Faupp>
{
public:
    Faupp() = default;
    Faupp(Faupp&& he) = default;
    Faupp(Faupp const& he) = default;

public: // requests
    bool operator()() override;

private: // Data
    FauppLexer m_fauppLexer;

private: // Bisonc++ external functions
    void error(char const *msg);
    int lex();
    void print();

private:  // Bisonc++ internals (auto-implemented).
    int parse(); // (auto-implemented)
    void executeAction(int ruleNr);
    void errorRecovery();
    int lookup(bool recovery);
    void nextToken();
    void print__();
};

#endif
