// lexer.hpp

#ifndef FauppLexer_H_INCLUDED_
#define FauppLexer_H_INCLUDED_

// Header file of FauppLexer base clase (FauppLexerBase).
// This file is automatically generated by flexc++, from faupp-lexer.ll.
#include "../../../.phantom-dir/faupp-lexer-phantom.hpp"
#include "../../../.phantom-dir/faupp-parser-phantom.hpp" // Tokens definition.

typedef FauppBase::Tokens__ FauppToken;
typedef FauppBase::STYPE__ FauppAttribute;

#include <cstdlib>  // EXIT_FAILURE macro.
#include <iostream> // cout, cerr, endl.
#include <string>

class FauppLexer : public FauppLexerBase
{
public:
    explicit FauppLexer(std::istream &in = std::cin,
                        std::ostream &out = std::cout);
    FauppLexer(std::string const &infile, std::string const &outfile);

    std::string const& matched() const;

    int lex();

private: // Flexc++ functions.
    int lex__();
    int executeAction__(size_t ruleNr);

    void print();
    void preCode();
};

#endif // FauppLexer_H_INCLUDED_
